import {
  FaTools,
  FaBolt,
  FaIndustry,
  FaUserGraduate,
  FaHandshake,
  FaFire,
  FaCogs,
  FaHardHat,
  FaWrench,
  FaPlug,
  FaLaptopCode,
  FaNetworkWired,
  FaSolarPanel,
  FaWarehouse,
  FaTruck,
  FaHospital,
  FaShieldAlt,
  FaClipboardCheck,
  FaChartLine,
  FaBuilding,
} from "react-icons/fa";

export const ICON_MAP = {
  FaTools,
  FaBolt,
  FaIndustry,
  FaUserGraduate,
  FaHandshake,
  FaFire,
  FaCogs,
  FaHardHat,
  FaWrench,
  FaPlug,
  FaLaptopCode,
  FaNetworkWired,
  FaSolarPanel,
  FaWarehouse,
  FaTruck,
  FaHospital,
  FaShieldAlt,
  FaClipboardCheck,
  FaChartLine,
  FaBuilding,
} as const;

export type IconKey = keyof typeof ICON_MAP;
